const cardsData = [
  {
    id: 1,
    type: "image",
    src: "img1.webp",
    text: "Ramotion",
    views: "10.7k",
    likes: 127,
  },
  {
    id: 2,
    type: "image",
    src: "img2.webp",
    text: "Emote",
    views: "5.4k",
    likes: 89,
  },
  {
    id: 3,
    type: "image",
    src: "img3.webp",
    text: "Muti",
    views: "7.2k",
    likes: 112,
  },
  {
    id: 4,
    type: "image",
    src: "img4.webp",
    text: "Recently updated",
    views: "8.3k",
    likes: 98,
  },
  {
    id: 5,
    type: "image",
    src: "img5.webp",
    text: "Trending now",
    views: "12.1k",
    likes: 145,
  },
  {
    id: 6,
    type: "image",
    src: "img6.webp",
    text: "Creative Design",
    views: "15.2k",
    likes: 210,
  },
  {
    id: 7,
    type: "image",
    src: "img7.webp",
    text: "Just added",
    views: "6.8k",
    likes: 76,
  },
  {
    id: 8,
    type: "image",
    src: "img8.webp",
    text: "New Release",
    views: "9.4k",
    likes: 134,
  },
  {
    id: 9,
    type: "image",
    src: "img9.webp",
    text: "Wix Studio",
    views: "11.6k",
    likes: 198,
  },
  {
    id: 10,
    type: "image",
    src: "img10.webp",
    text: "Top Rated",
    views: "14.5k",
    likes: 256,
  },
  {
    id: 11,
    type: "image",
    src: "img11.webp",
    text: "Editor's Pick",
    views: "13.7k",
    likes: 178,
  },
  {
    id: 12,
    type: "image",
    src: "img12.webp",
    text: "Modall",
    views: "16.2k",
    likes: 312,
  },
  {
    id: 13,
    type: "image",
    src: "img13.webp",
    text: "User Favorite",
    views: "33.2k",
    likes: 200,
  },
  {
    id: 14,
    type: "image",
    src: "img14.webp",
    text: "Roohi Khooi",
    views: "13.2k",
    likes: 300,
  },
  {
    id: 15,
    type: "image",
    src: "img15.webp",
    text: "Detail Studio",
    views: "19.2k",
    likes: 319,
  },
  {
    id: 16,
    type: "image",
    src: "img16.webp",
    text: "heatbeat",
    views: "9.2k",
    likes: 34,
  },
];
export default cardsData;
